version: "3.9"

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      NODE_ENV: production
      DB_HOST: postgres
    depends_on:
      postgres:
        condition: service_healthy
    restart: always
  postgres:
    image: postgres:latest
    container_name: swift_postgres
    restart: always
    environment:
      POSTGRES_USER: swift
      POSTGRES_PASSWORD: swift
      POSTGRES_DB: swiftdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U swift -d swiftdb"]
      interval: 10s
      retries: 5
      timeout: 5s

volumes:
  pgdata:
